INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu1', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu2', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu3', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu4', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu5', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu6', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu7', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu8', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu9', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu10', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu11', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu12', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu13', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu14', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu15', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu16', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu17', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu18', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu19', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu20', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu21', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu22', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu23', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu24', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu25', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu26', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu27', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu28', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu29', 'hannu123', 'hannu@hannu');
INSERT INTO resepti (nimi, raakaaineluokitus ,kayttotilanneluokitus, annosmaara, kayttajaid) VALUES ('kissapata', 'kissa', 'Pääruoka', 10, 2);
INSERT INTO resepti (nimi, raakaaineluokitus ,kayttotilanneluokitus, annosmaara, kayttajaid) VALUES ('kissapata2', 'kissa', 'Pääruoka', 10, 2);
INSERT INTO resepti (nimi, raakaaineluokitus ,kayttotilanneluokitus, annosmaara, kayttajaid) VALUES ('kissapata3', 'kissa', 'Pääruoka', 1, 2);
INSERT INTO resepti (nimi, raakaaineluokitus ,kayttotilanneluokitus, annosmaara, kayttajaid) VALUES ('kissapata10', 'kissa', 'Pääruoka', 1, 2);
INSERT INTO resepti (nimi, raakaaineluokitus ,kayttotilanneluokitus, annosmaara, kayttajaid) VALUES ('kissapata11', 'kissa', 'Pääruoka', 1000, 29);
INSERT INTO valmistusvaihe (reseptiid, jarjestysnumero, nimi, ohjeet, kuva) VALUES (1, 1, 'kissan paistaminen', 'paista kissa pannulla', 'http://img.avatv.fi/mn_kuvat/mtv3/helmi/minisaitit/kapalakerho/kissat/2012/03/1356549.jpg');
INSERT INTO valmistusvaihe (reseptiid, jarjestysnumero, nimi, ohjeet, kuva) VALUES (1, 2, 'kissan paistaminen2', 'paista kissa pannulla', 'http://img.avatv.fi/mn_kuvat/mtv3/helmi/minisaitit/kapalakerho/kissat/2012/03/1356549.jpg');
INSERT INTO valmistusvaihe (reseptiid, jarjestysnumero, nimi, ohjeet, kuva) VALUES (1, 3, 'kissan paistaminen3', 'paista kissa pannulla', 'http://img.avatv.fi/mn_kuvat/mtv3/helmi/minisaitit/kapalakerho/kissat/2012/03/1356549.jpg');
INSERT INTO valmistusvaihe (reseptiid, jarjestysnumero, nimi, ohjeet, kuva) VALUES (1, 4, 'kissan paistaminen4', 'paista kissa pannulla', 'http://img.avatv.fi/mn_kuvat/mtv3/helmi/minisaitit/kapalakerho/kissat/2012/03/1356549.jpg');
