INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu1', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu2', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu3', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu4', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu5', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu6', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu7', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu8', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu9', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu10', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu11', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu12', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu13', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu14', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu15', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu16', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu17', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu18', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu19', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu20', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu21', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu22', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu23', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu24', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu25', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu26', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu27', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu28', 'hannu123', 'hannu@hannu');
INSERT INTO kayttaja (kayttajatunnus, salasana, sahkoposti) VALUES ('Hannu29', 'hannu123', 'hannu@hannu');
INSERT INTO resepti (nimi, raakaaineluokitus ,kayttotilanneluokitus, annosmaara, kayttajaid) VALUES ('kissapata', 'kissa', 'Pääruoka', 10, 2);
INSERT INTO resepti (nimi, raakaaineluokitus ,kayttotilanneluokitus, annosmaara, kayttajaid) VALUES ('kissapata2', 'kissa', 'Pääruoka', 10, 2);
INSERT INTO resepti (nimi, raakaaineluokitus ,kayttotilanneluokitus, annosmaara, kayttajaid) VALUES ('kissapata3', 'kissa', 'Pääruoka', 1, 2);
INSERT INTO resepti (nimi, raakaaineluokitus ,kayttotilanneluokitus, annosmaara, kayttajaid) VALUES ('kissapata10', 'kissa', 'Pääruoka', 1, 2);
INSERT INTO resepti (nimi, raakaaineluokitus ,kayttotilanneluokitus, annosmaara, kayttajaid) VALUES ('kissapata11', 'kissa', 'Pääruoka', 1000, 29);
INSERT INTO raakaaine (nimi, yksikkohinta) VALUES ('vehnäjauho',2.75);
INSERT INTO raakaaine (nimi, yksikkohinta) VALUES ('sokeri',1.5);
INSERT INTO raakaaine (nimi, yksikkohinta) VALUES ('maito',1.65);
INSERT INTO raakaaine (nimi, yksikkohinta) VALUES ('voi',5);
INSERT INTO raakaaine (nimi, yksikkohinta) VALUES ('appelsiinituoremehu',1.1);
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet, kuva) VALUES (1, 'kissan paistaminen', 'paista kissa pannulla', 'http://img.avatv.fi/mn_kuvat/mtv3/helmi/minisaitit/kapalakerho/kissat/2012/03/1356549.jpg');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet, kuva) VALUES (1, 'kissan paistaminen2', 'paista kissa pannulla', 'http://img.avatv.fi/mn_kuvat/mtv3/helmi/minisaitit/kapalakerho/kissat/2012/03/1356549.jpg');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet, kuva) VALUES (1, 'kissan paistaminen3', 'paista kissa pannulla', 'http://img.avatv.fi/mn_kuvat/mtv3/helmi/minisaitit/kapalakerho/kissat/2012/03/1356549.jpg');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet, kuva) VALUES (1, 'kissan paistaminen4', 'paista kissa pannulla', 'http://img.avatv.fi/mn_kuvat/mtv3/helmi/minisaitit/kapalakerho/kissat/2012/03/1356549.jpg');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (2, 'kissan paistaminen21', 'paista kissa pannulla21');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (2, 'kissan paistaminen22', 'paista kissa pannulla22');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (2, 'kissan paistaminen23', 'paista kissa pannulla23');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (2, 'kissan paistaminen24', 'paista kissa pannulla24');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (2, 'kissan paistaminen25', 'paista kissa pannulla25');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (2, 'kissan paistaminen26', 'paista kissa pannulla26');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (3, 'kissan paistaminen31', 'paista kissa pannulla31');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (3, 'kissan paistaminen32', 'paista kissa pannulla32');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (3, 'kissan paistaminen33', 'paista kissa pannulla33');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (3, 'kissan paistaminen34', 'paista kissa pannulla34');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (5, 'kissan paistaminen51', 'paista kissa pannulla51');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (5, 'kissan paistaminen52', 'paista kissa pannulla52');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (5, 'kissan paistaminen53', 'paista kissa pannulla53');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (5, 'kissan paistaminen54', 'paista kissa pannulla54');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (5, 'kissan paistaminen55', 'paista kissa pannulla55');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (5, 'kissan paistaminen56', 'paista kissa pannulla56');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (4, 'kissan paistaminen41', 'paista kissa pannulla41');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (4, 'kissan paistaminen42', 'paista kissa pannulla42');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (4, 'kissan paistaminen43', 'paista kissa pannulla43');
INSERT INTO valmistusvaihe (reseptiid, nimi, ohjeet) VALUES (4, 'kissan paistaminen44', 'paista kissa pannulla44');
INSERT INTO maara (reseptiid, vaihenumero, raakaaineid, maara, mittayksikko) VALUES (2, 6, 3, 4.5, 'dl');
INSERT INTO maara (reseptiid, vaihenumero, raakaaineid, maara, mittayksikko) VALUES (2, 6, 4, 4.5, 'dl');
INSERT INTO maara (reseptiid, vaihenumero, raakaaineid, maara, mittayksikko) VALUES (2, 6, 5, 4.5, 'dl');
INSERT INTO maara (reseptiid, vaihenumero, raakaaineid, maara, mittayksikko) VALUES (3, 11, 3, 4.5, 'dl');
INSERT INTO maara (reseptiid, vaihenumero, raakaaineid, maara, mittayksikko) VALUES (4, 22, 3, 4.5, 'dl');
INSERT INTO maara (reseptiid, vaihenumero, raakaaineid, maara, mittayksikko) VALUES (4, 23, 3, 4.5, 'dl');
INSERT INTO maara (reseptiid, vaihenumero, raakaaineid, maara, mittayksikko) VALUES (4, 23, 2, 4.5, 'dl');
INSERT INTO maara (reseptiid, vaihenumero, raakaaineid, maara, mittayksikko) VALUES (4, 24, 3, 4.5, 'dl');
